name: build-application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: npm ci
      - name: Run prod build
        run: npm run build:prod
        if: always()
      - name: Linting TS
        run: npm run lint:ts
        if: always()
      - name: Linting Styles
        run: npm run lint:scss
        if: always()
      - name: Run unit tests
        run: npm run test:unit
        if: always()
      - name: Build Storybook
        run: npm run storybook:build
        if: always()
      - name: Run Visual UI Regression Testing
        uses: lost-pixel/lost-pixel@v3.0.3
